apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: {{ .Release.Name }}
  name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      k8s-app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        k8s-app: {{ .Release.Name }}
    spec:
      containers:
        - image: {{ .Values.image }}:{{ .Values.tag }}
          imagePullPolicy: IfNotPresent
          name: {{ .Release.Name }}
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
          volumeMounts:
            - mountPath: /go/src/code
              name: code
      dnsPolicy: ClusterFirst
      nodeName: {{ .Values.nodeName }} # node name
      restartPolicy: Always
      schedulerName: default-scheduler
      volumes:
        - hostPath:
            path: {{ .Values.codePath}} # /path/to/code
            type: Directory
          name: code
