apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  ports:
    - nodePort: {{ .Values.nodePort }}
      port: 2345
      protocol: TCP
      targetPort: 2345
  selector:
    k8s-app: {{ .Release.Name }}
  sessionAffinity: None
  type: NodePort
