apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: {{ .Release.Name }}-cacher
    app.kubernetes.io/name: {{ .Release.Name }}-cacher
    app: {{ .Release.Name }}-cacher
    version: "1.0"
  name: {{ .Release.Name }}-cacher
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: {{ .Release.Name }}-cacher
      app.kubernetes.io/name: {{ .Release.Name }}-cacher
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: {{ .Release.Name }}-cacher
        app.kubernetes.io/name: {{ .Release.Name }}-cacher
        app: {{ .Release.Name }}-cacher
        version: "1.0"
    spec:
      containers:
        - image: {{ .Values.cacher.image }}:{{ .Values.cacher.tag}}
          imagePullPolicy: IfNotPresent
          name: {{ .Release.Name }}-cacher
          resources: { }
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: { }
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
          volumeMounts:
            - mountPath: /config.yaml
              name: config
              subPath: config.yaml
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: my-harbor
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: { }
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 256
            name: {{ .Release.Name }}-cacher-config
            optional: false
          name: config
