apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ui
spec:
  ports:
    - name: http-default
      port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    k8s-app: {{ .Release.Name }}-ui
  sessionAffinity: None
  type: ClusterIP
